name: Run Otaga TSN Linter

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'

      - name: Install TSN Abstracter
        run: pip install tsn-abstracter

      - name: Run Python script
        run: python Otaga.py